#ifndef LIBACQUIREPET_GLOBAL_H
#define LIBACQUIREPET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBACQUIREPET_LIBRARY)
#  define LIBACQUIREPET_EXPORT Q_DECL_EXPORT
#else
#  define LIBACQUIREPET_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBACQUIREPET_GLOBAL_H
